### ISSUE TITLE
AI doesn't work anymore with new version of majsoul.

### ISSUE THREAD

**Issue by mraymes** [zhangjk95/MahjongAI#25] opened 2019-10-09 02:40 UTC
Output:
```
Login succeeded.
Game matching timed out.
Unexpectedly disconnected.
Client closed.
Login succeeded.
```
... and so on.

**Comment by Eureka0225** [comment] 2019-10-09 15:02
so, i think we can close this issue------------------ 原始邮件 ------------------
发件人: "re-div"<notifications@github.com>
发送时间: 2019年10月9日(星期三) 晚上7:43
收件人: "zhangjk95/MahjongAI"<MahjongAI@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [zhangjk95/MahjongAI] AI doesn't work anymore with new version ofmajsoul. (#25)



It was intended. See #24.
 
&mdash;

**Closed** 2019-10-09 16:21 UTC
